const data = [
  {
    name: "bulbasaur",
    height: 7,
    is_default: true,
    weight: 69,
    birthday: "2-6-2022",
    url: "https://pokeapi.co/api/v2/pokemon/1/",
    front_default: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png",
  },
  {
    name: "ivysaur",
    height: 10,
    is_default: true,
    weight: 130,
    url: "https://pokeapi.co/api/v2/pokemon/2/",
    front_default: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png",
  },
  {
    name: "venusaur",
    height: 20,
    is_default: true,
    weight: 1000,
    url: "https://pokeapi.co/api/v2/pokemon/3/",
    front_default: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png",
  },
  {
    name: "charmander",
    height: 6,
    is_default: true,
    weight: 85,
    url: "https://pokeapi.co/api/v2/pokemon/4/",
    front_default: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png",
  },
  {
    name: "charmeleon",
    height: 11,
    is_default: true,
    weight: 190,
    url: "https://pokeapi.co/api/v2/pokemon/5/",
    front_default: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png",
  },
  {
    name: "charizard",
    height: 17,
    is_default: true,
    weight: 905,
    url: "https://pokeapi.co/api/v2/pokemon/6/",
    front_default: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png",
  },
  {
    name: "squirtle",
    height: 5,
    is_default: true,
    weight: 90,
    url: "https://pokeapi.co/api/v2/pokemon/7/",
    front_default: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png",
  },
  {
    name: "wartortle",
    height: 10,
    is_default: true,
    weight: 225,
    url: "https://pokeapi.co/api/v2/pokemon/8/",
    front_default: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/8.png",
  },
  {
    name: "blastoise",
    height: 16,
    is_default: true,
    weight: 855,
    url: "https://pokeapi.co/api/v2/pokemon/9/",
    front_default: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png",
  },
  {
    name: "caterpie",
    height: 3,
    is_default: false,
    weight: 29,
    url: "https://pokeapi.co/api/v2/pokemon/10/",
    front_default: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10.png",
  },
  {
    name: "metapod",
    height: 7,
    is_default: false,
    weight: 99,
    url: "https://pokeapi.co/api/v2/pokemon/11/",
    front_default: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/11.png",
  },
  {
    name: "butterfree",
    height: 7,
    is_default: false,
    weight: 99,
    url: "https://pokeapi.co/api/v2/pokemon/12/",
    front_default: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/12.png",
  },
  {
    name: "weedle",
    height: 11,
    is_default: false,
    weight: 320,
    url: "https://pokeapi.co/api/v2/pokemon/13/",
    front_default: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/13.png",
  },
  {
    name: "kakuna",
    height: 3,
    is_default: false,
    weight: 32,
    url: "https://pokeapi.co/api/v2/pokemon/14/",
    front_default: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/14.png",
  },
  {
    name: "beedrill",
    height: 6,
    is_default: false,
    weight: 100,
    url: "https://pokeapi.co/api/v2/pokemon/15/",
    front_default: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/15.png",
  },
  {
    name: "pidgey",
    height: 6,
    is_default: false,
    weight: 85,
    url: "https://pokeapi.co/api/v2/pokemon/16/",
    front_default: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/16.png",
  },
  {
    name: "pidgeotto",
    height: 11,
    is_default: false,
    weight: 300,
    url: "https://pokeapi.co/api/v2/pokemon/17/",
    front_default: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/17.png",
  },
  {
    name: "pidgeot",
    height: 15,
    is_default: false,
    weight: 395,
    url: "https://pokeapi.co/api/v2/pokemon/18/",
    front_default: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/18.png",
  },
  {
    name: "rattata",
    height: 3,
    is_default: false,
    weight: 35,
    url: "https://pokeapi.co/api/v2/pokemon/19/",
    front_default: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/female/19.png",
  },
  {
    name: "raticate",
    height: 7,
    is_default: false,
    weight: 185,
    url: "https://pokeapi.co/api/v2/pokemon/20/",
    front_default: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/female/20.png",
  },
];
